# -*- coding: utf-8 -*-
"""text_find.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrnwbfMc6ypJnUHpUHw6c2l2KUwCG9Mh
"""

# !pip install tensorflow-gpu==2.0.0-rc1
import tensorflow as tf

# mnist = tf.keras.datasets.mnist

# (x_train, y_train), (x_test, y_test) = mnist.load_data()
# x_train, x_test = x_train / 255.0, x_test / 255.0

import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
def count_codePoint(str):
    counter = np.zeros(65535) # Unicode 코드 포인트 저장 배열
    for i in range(len(str)):
        code_point = ord(str[i])
        if code_point > 65535 :
            continue
        counter[code_point] += 1
    counter = counter / len(str)
    return  counter
ko_str = '이것은 한국어 문장입니다.'
ja_str = 'これは日本語の文章です。'
en_str = 'This is English Sentences.'
x_train = [count_codePoint(ko_str),
           count_codePoint(ja_str),
           count_codePoint(en_str)]
y_train = ['ko','ja','en']
clf = GaussianNB()
clf.fit(x_train, y_train)
ko_test_str = '안녕하세요'
ja_test_str = 'こんにちは'
en_test_str = 'Hello'
x_test =  [count_codePoint(en_test_str),
           count_codePoint(ja_test_str),
           count_codePoint(ko_test_str)]
y_test =  ['en','ja','ko']
y_pred = clf.predict(x_test)
print(y_pred)
print('정답률 : ', accuracy_score(y_test, y_pred))

